### PR TITLE
Updated to v1.0.1

### PR DESCRIPTION
**Pull request by Chilipp**

### CODE REVIEW

**Comment by jakirkham** [comment]
The token here is expired. Please see the ["Near term" plan]( https://github.com/conda-forge/conda-forge.github.io/issues/426#issuecomment-321897876 ) on how to fix this.

**Comment by Chilipp** [comment]
Thanks, I will do this and close this PR for now

**Comment by jakirkham** [comment]
Sorry if I gave you the impression this should be closed. It can certainly be open. Just encouraging you to resubmit the recipe in `master` to `staged-recipes` so that the token can be updated in the feedstock.

**Comment by Chilipp** [comment]
I merge this now because the failed tests on appveyor only came from CondaHTTPError (see 
[appveyor build 1.0.8](https://ci.appveyor.com/project/conda-forge/psyplot-gui-feedstock/build/1.0.8)

**Pull request merged**
